apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ex-rails-app
  namespace: staging
spec:
  releaseName: ex-rails-app
  install:
    #disableWait: true
    disableHooks: true
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    disableHooks: true
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: ./eh-app
      sourceRef:
        kind: GitRepository
        name: eh-helm-chart
        namespace: flux-system
  interval: 1m0s
  valuesFrom:
  - kind: Secret
    name: ex-rails-app-vault
    valuesKey: values.yaml
    optional: true
  values:
    image:
      repository: ex-rails-app
      tag: '0.1'
      pullPolicy: IfNotPresent

    # Override name of the chart
    nameOverride: ""

    # Override fully qualified app name
    fullnameOverride: "ex-rails-app"

    additionalAnnotations:
      owner: "squad-platform"

    # Add web/rpc/worker containers and corresponding services
    procs:
    - name: web
      command: ["bundle", "exec", "puma", "-p", "80", "-C", "config/puma.rb"]
      replicas: 2
      probe:
        enabled: true
        port: 80
        path: /health
      #liveness:
        #type: http
        #port: 80
        #path: /healthz
        #period: 10
        #threshold: 5
        #initialDelay: 30
      #readiness:
        #type: http
        #port: 80
        #path: /healthz
        #period: 10
        #threshold: 5
        #initialDelay: 30
      ports:
      - name: http
        port: 80
      resources:
        requests:
          cpu: 50m
          memory: 100M
        limits:
          cpu: 500m
          memory: 500M

    - name: rpc
      command: ["bundle", "exec", "puma", "-p", "80", "-C", "config/puma.rb"]
      replicas: 2
      ports:
      - name: http
        port: 80
      liveness:
        type: tcp
        port: 80
        period: 10
        threshold: 5
        initialDelay: 30
      resources:
        requests:
          cpu: 50m
          memory: 100M
        limits:
          cpu: 500m
          memory: 500M

    - name: worker
      command: ["bundle", "exec", "sidekiq"]
      resources:
        requests:
          cpu: 5m
          memory: 100M
        limits:
          cpu: 100m
          memory: 500M
      replicas: 1

    cronjobs:
    - name: print_time
      schedule: "* * * * *"
      command: ["bundle", "exec", "rake", "test:print_time"]
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobDeadline: 7200       # 2 hours

    databaseMigration:
      enabled: false
      jobDeadline: 300
      backoffLimit: 1
      # Required
      command: ["bundle", "exec", "rake", "db:migrate"]
      migrationPlan: "pre"

    upgradeNotify:
      enabled: false
      notifyClientImage: "979797940137.dkr.ecr.ap-southeast-2.amazonaws.com/hero2-notifier:latest"
      endpoint: "http://hero2-dev-api.flux:80/notify/deploy_success"

    publishSentryRelease:
      enabled: true
      projectSlug: ex-rails-app

    env:
      VAULT_VERSION: 5
      RAILS_ENV: production
      APP_ENV: application
      REDIS_URL: "redis-ex-rails-app.stateful:6379"
      USERNAME: '1234'
