apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: {{ include "my-rails-app.fullname" . }}
  generation: 1
  labels:
    app: {{ include "my-rails-app.name" . }}
    chart: {{ include "my-rails-app.chart" . }}
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "my-rails-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-rails-app.name" . }}
    spec:
      containers:
        - command:
          - rails
          - s
          - -p
          - "3001"
          - -b
          - 0.0.0.0
          env:
          - name: APP_PROC_NAME
            value: 'web'
          - name: APP_NAME
            value: 'ex-rails-app-web'
          - name: DATABASE_PWD
            value: 'P@ssword17e3'
          - name: DATABASE_HOST
            value: 'postgres-test.dev'
          - name: DATABASE_USR
            value: 'root'
          - name: DATABASE_NAME
            value: 'rails_app'
          - name: DATABASE_PORT
            value: '5432'
          stdin: true
          tty: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
