apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-rails-app.fullname" . }}
  labels:
    app: {{ include "my-rails-app.name" . }}
    chart: {{ include "my-rails-app.chart" . }}
  namespace: dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-rails-app.name" . }}
