apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-mail
  namespace: stateful
spec:
  releaseName: redis-mail
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.3.4"
      install:
        remediation:
          retries: 3
      upgrade:
        remediation:
          retries: 3
  interval: 1h0m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
  values:
    usePassword: false
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
