apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: eh-helm-chart
  namespace: flux-system
spec:
  interval: 1m
  url: git@github.com:Thinkei/eh-helm-chart.git
  ref:
    branch: develop
  secretRef:
    name: eh-helm-ssh-credentials
