---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: my-rails-app
  namespace: dev
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: my-rails-app
  chart:
    git: git@github.com:nguyenductoan/flux-get-started
    ref: master
    path: charts/my-rails-app
  values:
    replicaCount: 1

    image:
      repository: k8s.gcr.io/echoserver
      tag: 1.4
      pullPolicy: IfNotPresent

    service:
      type: NodePort
      port: 80
      externalPort: 80
      internalPort: 8080

    ingress:
      enabled: false
      annotations: {}
      paths: []
      hosts:
        - chart-example.local
      tls: []

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}
